### ISSUE TITLE
Unify the format of returned measurement data

### ISSUE THREAD

**Issue by co9olguy** [XanaduAI/strawberryfields#107]
We should make the format (type, shape) of returned measurement results more uniform. Currently we sometimes return scalars, arrays, lists, tuples, etc. 

With the new `Results` object being created, now is the time to refactor the return types for various backends, and have a unified standard expressed in `Results`. 

This may also have relevance for register values.

Things to take into account:
1. shots
1. batch_size
1. number of measured modes
1. whether the user entered measured modes out of order -- should we return them in same order requested?

**Comment by smite** [comment]
A summary of my posts in the PR:

* I think internally (backend API, `Measurement.apply` etc.) measurement samples should always be returned in a similar 2d array (even if shots==1): `shape == (modes, shots)`. Only measured modes should have rows (or cols, does not really matter) in the array, and the results should be in the same order as they were requested (the `modes` argument).

Returning measurement samples to the user (inside the `Result` object):
I don't think returning Nones for the non-measured systems is very useful.

Options:

1.   A dictionary, mapping indices of measured subsystems to sample lists or 1d-arrays: `result.samples = {0: [0.32, 1.43, -0.32], 2: [0, 4, 5]}`
 2.   A 2d-array with just the measured subsystems, in subsystem index order, leaving it to the user to remember what they are (risky!): `result.samples = array([[0.32, 1.43, -0.32], [0, 4, 5]], dtype=float)`
 3.   An array like in 2., but with an additional list/1d-array of subsystem indices to label the rows: `result.measured_modes = [0, 2]`
 4.  Is there a way in Numpy to label array rows/columns? If there is, 2. and 3. could be combined into a single labeled array.

**Comment by smite** [comment]
The `Result` class can also be given a property method (or several) for returning the samples in another format, e.g. `result.samples_array`

**Comment by josh146** [comment]
How about, as @smite suggested for the user facing results:

* `results.samples = {0: [0.32, 1.43, -0.32], 2: [0, 4, 5]}`

* `results.samples_array = array([[0.32, 1.43, -0.32], [0, 4, 5]], dtype=float)`

* I don't see any downside to also providing `result.measured_modes = [0, 2]`

For the backend API, I agree with `shape == (modes, shots)`.

**Comment by co9olguy** [comment]
I'm in favour of all this. Let's do exactly as @josh146 outlined above --^

**Comment by smite** [comment]
What about batch_size? How should it work?

**Comment by co9olguy** [comment]
I added some preliminary tests for this. Conventionally, batch axis is always first.
So 'results_array.shape==(batch_size, modes, shots)'

**Comment by smite** [comment]
Is this also how it's handled internally? So if you have batching on, the internal representation of the samples is always a 3d array?

**Comment by co9olguy** [comment]
If batch mode is used, then deep in the guts of the TF Backend, everything is represented as tensors with shape `(batch_size, ...)`. Measurements are currently returned as a Tensor/array of shape `(batch_size,)`. The only exception is for `measure_fock` on N modes, which I believe is returned as `tuple(batch0, batch1,...)` where `batchX.shape==(batch_size)`

**Comment by co9olguy** [comment]
btw I'm open to changing this if we have better suggesitons. Previously there was only one case where a measurement result was returned that had more than one axis (`measure_fock` in TF backend with `batch_size != 1`), so it was decided semi-arbitrarily how this should look

**Comment by thisac** [comment]
Obsolete issue. Results should now be unified across backends (incl. remote).
