### ISSUE TITLE
Name state_options and DeviceSpecs to be more consistent

### ISSUE THREAD

**Issue by josh146** [XanaduAI/strawberryfields#120]
> @smite @josh146 Some other points that came up when revising docs, to make structure of library more consistent:
> 
>     * [ ]  put the `modes` argument from `eng.run` into `state_options` dictionary
> 
>     * [ ]  rename `state_options` dictionary to `result_options`, `return_options`, or `run_options` (last one is my favourite, since TFBackend actually needs these options during execution)
> 
>     * [ ]  rename `DeviceSpecs` to `CircuitSpecs`

I'm thinking these naming refactors should be spun out as a separate PR to the docs one (should be final task before release)

_Originally posted by @co9olguy in https://github.com/XanaduAI/strawberryfields/pull/118#issuecomment-508866646_

**Comment by smite** [comment]
* Modes into `state_options`: good, the check in `LocalEngine.run()` whether to create a state object at all can be replaced with `if state_options:`

* CircuitSpecs is ok too

* Renaming `state_options`: note that currently also the generic **kwargs are treated as "run options", we should first make a list of all the keyword arguments we use when running Programs, and which classes need them.

**Comment by josh146** [comment]
Done in #121
