### ISSUE TITLE
Deprecate the `Measure` shortcut

### ISSUE THREAD

**Issue by josh146** [XanaduAI/strawberryfields#123]
We should deprecate `Measure`. It doesn't really serve the same purpose as `MeasureX` and `MeasureP` (which are shortcuts to `MeasureHomodyne` with specific values of `phi`), except for typing 4 less characters.

At the same time, it makes the documentation confusing, and goes against the zen of Python:
> There should be one-- and preferably only one --obvious way to do it.

_Originally posted by @josh146 in https://github.com/XanaduAI/strawberryfields/pull/121_

**Comment by smite** [comment]
What's the deprecation policy in Strawberry Fields? Do we use `DeprecationWarning`?

**Comment by josh146** [comment]
We haven't officially deprecated anything in SF yet, but when we deprecated `qml.expval.Observable` in PennyLane, we used `DeprecationWarning`. So let's use it here as well.
