### ISSUE TITLE
GaussianBackend.state() raises an IndexError if all modes in the state have been deleted

### ISSUE THREAD

**Issue by smite** [XanaduAI/strawberryfields#13]
#### Issue description

* *Expected behavior:* It should return a degenerate/empty GaussianState object instead.

#### Minimal example

    import strawberryfields as sf
    from strawberryfields.ops import *

    eng, q = sf.Engine(num_subsystems=1)
    with eng:
        Del | q

    s = eng.run('gaussian')

**Comment by josh146** [comment]
Hey Ville, does this happen with the Fock backends as well?

**Comment by smite** [comment]
On 17 May 2018 at 01:02, Josh Izaac <notifications@github.com> wrote:

> Hey Ville, does this happen with the Fock backends as well?
>

No, the Fock backend returns a BaseFockState object with 0 modes and a
state representation which is just the complex scalar 1, which is
reasonable.


-- 
        Ville Bergholm
        ville.bergholm@iki.fi
        phone (Finland) +358-44-5722802

**Comment by smite** [comment]
I guess in the gaussian case it should return a lenght-0 means vector and a 0 times 0 covariance matrix?
