### ISSUE TITLE
Typo in Boson sampling tutorial

### ISSUE THREAD

**Issue by cheechonghian** [XanaduAI/strawberryfields#132]
Line 139 in code has a typo: `t_r_amplitudes = [(np.cos(q), np.exp(p)*np.sin(q)) for q,p in BSargs]` 
This reproduce the output
`t_r_amplitudes = [(0.7106321693790166, 1.6589803738428945), (0.9979488597798205, 0.107300799784619), (0.8902056193228912, 0.5124100188873868), (0.8456577421648502, 0.6211557100515316), (0.9912611127695864, 0.35664937353562604), (0.9520280351333678, 0.42272440930112964), (0.9069543062416473, 0.45622069547345073), (0.9061100348574156, 0.7830305118939467)]`

We want `r=e^{i\phi}\*sin(\theta)` therefore it has to be calculated as `np.exp(1j*p)*np.sin(q))` not  `np.exp(p)*np.sin(q))`

 Line 139 in code should be correct as: `t_r_amplitudes = [(np.cos(q), np.exp(1j*p)*np.sin(q)) for q,p in BSargs]` 

This reproduce the output
`t_r_amplitudes =[(0.7106321693790166, (0.4602032449982007+0.5321793806009387j)), (0.9979488597798205, (0.05566547093254029+0.03161374084183274j)), (0.8902056193228912, (0.4524124415797152+0.0534503323640587j)), (0.8456577421648502, (0.5275960535594109+0.08065598170739026j)), (0.9912611127695864, (0.07187201856963185+0.11061563749094347j)), (0.9520280351333678, (0.29017650247396554+0.09716078289143039j)), (0.9069543062416473, (0.4198885288947347+0.03357841110516997j)), (0.9061100348574156, (0.3453586019763475+0.24431954643792997j))]`

**Comment by co9olguy** [comment]
Thanks @cheechonghian, I've corrected the typo in PR #133
