### ISSUE TITLE
UserWarning when using GraphEmbed for GBS

### ISSUE THREAD

**Issue by trbromley** [XanaduAI/strawberryfields#138]
#### Issue description

When using `GraphEmbed` to run a GBS-type circuit, I get the following warning:

> UserWarning: Cannot simulate non-Gaussian states. Conditional state after Fock measurement has not been updated.

The blackbird code resulting in this warning is:

``` python
with p.context as q:
    sf.ops.GraphEmbed(A, mean_photon_per_mode=mean_photon_per_mode) | q
    sf.ops.Measure | q
```

a full MWE is also below.

#### System information

* **Operating system:**
Ubuntu 18.04.2 LTS

* **Strawberry Fields version:**
0.11.1

* **Python version:**
Python 3.6.3 

* **NumPy, SciPy, and Tensorflow versions:**

  numpy==1.16.3
  scipy==1.2.1
  tensorflow==1.3.0

* **Installation method:**

  Installed by cloning `master` branch (commit e034e0b2fc74d166753ccd22648ac7c049e42ee2) 
  of SF and using `pip install -e .`

#### Source code and tracebacks

MWE:

``` python
import strawberryfields as sf
import numpy as np

mean_photon_per_mode = 1.
nodes = 6
shots = 10

A = np.ones(shape=(nodes, nodes))
p = sf.Program(nodes)

with p.context as q:
    sf.ops.GraphEmbed(A, mean_photon_per_mode=mean_photon_per_mode) | q
    sf.ops.Measure | q

p = p.compile("gbs")

eng = sf.LocalEngine(backend="gaussian")
samples = eng.run(p, run_options={"shots": shots}).samples
```

**Comment by co9olguy** [comment]
As expected, no harm here
