### ISSUE TITLE
TFBackend is missing the new backend.reset() functionality

### ISSUE THREAD

**Issue by smite** [XanaduAI/strawberryfields#15]
#### Issue description

The TensorFlow backend is currently lacking the new backend.reset(cutoff_dim=new_value) functionality. Consequently

    python3 tests/test_utils.py --backend=tf

currently fails. (Gaussian and Fock backends are OK.)

* *Expected behavior:* TFBackend.reset() should update the cutoff dimension if requested, and afterwards behave as if it was originally initialized with the new cutoff value.

The fix should be committed into the tf_complications branch.

**Comment by co9olguy** [comment]
I added this functionality in 0e4acd6.
@smite can you add some new relevant tests for the expected new behaviour? I don't feel that the previously failing tests in `test_utils` were capturing this directly

**Comment by smite** [comment]
I added test_eng_reset() added in test_toolchain.py, which test changing engine/backend parameters during reset in 1e54f02ef843d934d3d9f210ffca0ecbdca8a6e0.
