### ISSUE TITLE
Incorrect action of CXgate

### ISSUE THREAD

**Issue by nquesada** [XanaduAI/strawberryfields#168]
The version of the CX gate implemented in ops seems to have the wrong order of the beamsplitter relative to what is reported in the conventions page. This might be a bug

**Comment by nquesada** [comment]
This bug also implies that the gate teleportation test and example need to be refactored using the correct behaviour of the gate. This is also true for any other test/example that uses the CX and CZ gates

**Comment by nquesada** [comment]
The CXgate by definition should have the following behaviour

CX(s) |x_1>|x_2> = |x_1>|x_2+s x_1>

where |x_i> is a position eigenstate.

Its current implementation is correct. For example testing this behaviour for x_1=2 and x_2=1 
```
sf.hbar = 2
prog = sf.Program(2)
eng = sf.Engine("gaussian")
r = 3
x1 = 2
x2 = 1
s = 0.5

with prog.context as q:
    Sgate(r) | q[0]
    Xgate(x1) | q[0]
    Sgate(r) | q[1]
    Xgate(x2) | q[1]
    #CXgate(s)| q
state = eng.run(prog).state
```
we obtain the vector of means

![image](https://user-images.githubusercontent.com/991946/63463607-85dcf900-c42b-11e9-85a3-45952269c4cb.png)

The implementation is correct but the description in the conventions page is wrong. The order of the beamsplitter gates needs to be updated

**Comment by nquesada** [comment]
Addressed in https://github.com/XanaduAI/strawberryfields/pull/169 .
It would be nice to add the code above as a unit test. Not sure where though. Any ideas @josh146 ?

**Comment by josh146** [comment]
This would be the perfect test to add to `tests/integration/test_decompositions_integration.py`. The tests in this file double check that the frontend-defined decomps do the correct things on the backends.

We should ideally have tests for _all_ decomposed gates - `S2gate`, `CZgate`, `Pgate`, etc.
