### ISSUE TITLE
Xanadu interactive issues

### ISSUE THREAD

**Issue by OneDonMateo** [XanaduAI/strawberryfields#185]
Could it be possible to access Xanadu interactive from the python? 
I have two issues right now related to this question:
1) I would like to import inside Xanadu Interactive my code in Blackbird. It takes for me long time to add all BeamSplitters and set up them properly 0.5 or 1 plus other operators
2) Would it be possible to add to Strawberry simulator possibility to display Wigner function on 3D planes (I will be able to rotate this view like right now is possible on interactive). Currently is only possible to prepare a graph from data. I know this is more related to 3D display in python, but you have a code for display Wigner in interactive :)
I really like movies about changes of Wigner function, but it's not so easy to make those.

**Comment by co9olguy** [comment]
Thanks for your interest in Strawberry Fields @OneDonMateo!

We can consider number 1 as a feature when we update Strawberry Fields interactive. But bear in mind that this might take some time before it is updated.

Number 2, however, we might be able to help a little easier. We have some code on the server side for generating these plots. As a quick first step, we might be able to open-source that code as a separate repo. @josh146 how easy would it be to provide the that code?

**Comment by josh146** [comment]
> @josh146 how easy would it be to provide the that code?

The visualization is done using the open source Python plot.ly library, so shouldn't be too hard at all!
