### ISSUE TITLE
Rectangular symmetric decomposition returns two values

### ISSUE THREAD

**Issue by heltluke** [XanaduAI/strawberryfields#197]
#### Issue description

The return of `strawberryfields.decompositions.rectangular_symmetric(unitary)` is only two values long and not three, as might be expected from its test function https://github.com/XanaduAI/strawberryfields/blob/master/tests/frontend/test_decompositions.py#L308.

* *Expected behavior:* (What you expect to happen)
I expect `tlist, _, _, = strawberryfields.decompositions.rectangular_symmetric(unitary)` to give me a tlist.

* *Actual behavior:* (What actually happens)
Instead, I am told that there are not enough values to unpack.

* *Reproduces how often:* (What percentage of the time does it reproduce?)
100%
In fact, the test itself appears to fail.

* *System information:* (post the output of `import stawberryfields as sf; sf.about()`)

Strawberry Fields: a Python library for continuous-variable quantum circuits.
Copyright 2018-2019 Xanadu Quantum Technologies Inc.

Python version:            3.6.7
Platform info:             Windows-10-10.0.18362-SP0
Installation path:         C:\Users\Luke\Anaconda3\envs\SFields\lib\site-packages\strawberryfields
Strawberry Fields version: 0.11.1
Numpy version:             1.17.2
Scipy version:             1.3.1
Hafnian version:           0.6.1
Blackbird version:         0.2.1
TensorFlow version:        1.3.0

#### Source code and tracebacks
![image](https://user-images.githubusercontent.com/31250931/65355171-5272c300-dbbf-11e9-8b5e-64d5e21a6a64.png)
![image](https://user-images.githubusercontent.com/31250931/65355195-61597580-dbbf-11e9-987c-ed9b1e29b989.png)

**Comment by co9olguy** [comment]
@heltluke same as issue #192?

**Comment by heltluke** [comment]
@co9olguy related, but also a v0.11 v 0.12 issue, I believe.

**Comment by josh146** [comment]
I believe this is now solved in SF master as #196 has been merged.
