### ISSUE TITLE
Possible Bug in Interferometer or Ket

### ISSUE THREAD

**Issue by nquesada** [XanaduAI/strawberryfields#214]
I am trying to run the following circuit where two modes are prepared in a two-mode Fock state and are sent into an interferometer:

```python

import numpy as np
import strawberryfields as sf 
from strawberryfields.ops import *
from strawberryfields.utils import random_interferometer as haar_measure

cutoff = 15
l=2
m=[2,1]
n=[1,1]

U = haar_measure(l)
ketn1 = np.zeros([cutoff], dtype=np.complex128)
ketn1[n[0]] = 1.0
ketn2 = np.zeros([cutoff], dtype=np.complex128)
ketn2[n[1]] = 1.0
ketn = np.tensordot(ketn1, ketn2, axes = 0)

in_state = ketn1
sf.hbar = 1
prog = sf.Program(l)
eng = sf.Engine("fock", backend_options={"cutoff_dim": cutoff})
with prog.context as q:
    Ket(in_state) | q
    Interferometer(U)|q
state = eng.run(prog).state
```
when I try to run it I get the following sequence of errors:

![image](https://user-images.githubusercontent.com/991946/66597749-9d07af80-eb6d-11e9-9544-a351b7cd262c.png)

This is the output of sf.version():
```
Strawberry Fields: a Python library for continuous-variable quantum circuits.
Copyright 2018-2019 Xanadu Quantum Technologies Inc.

Python version:            3.6.8
Platform info:             Linux-4.15.0-65-generic-x86_64-with-debian-stretch-sid
Installation path:         
Strawberry Fields version: 0.12.0-dev
Numpy version:             1.16.4
Scipy version:             1.2.1
The Walrus version:           0.9.0-dev
Blackbird version:         0.2.0
TensorFlow version:        1.6.0
```
A (possibly) related issue is that when I remove the line with the interferometer and do ```state.ket()``` I get nothing back.

**Comment by co9olguy** [comment]
What is the shape of `in_state` in your code?

**Comment by josh146** [comment]
It is [15, 15], I believe, which should be fine (unless I am forgetting a detail about the `Ket` operation!)

**Comment by co9olguy** [comment]
From a quick glance at the code example above, it seems to have a shape of `(15,)`

**Comment by co9olguy** [comment]
Just trying to understand here: the text says the goal is to create a two-mode Fock state, but it seems that only a one-mode Fock state is created in code. 

Is the code given above exactly the code that gives the error?

**Comment by nquesada** [comment]
I think you are right @co9olguy `in_state` should be equal to `ketn` *not* `ketn1`

**Comment by nquesada** [comment]
Sorry for all the confusion. It was my fault. The shape of the input numpy array was wrong.

**Comment by co9olguy** [comment]
@nquesada Does computation execute successfully when corrected code is run?

**Comment by nquesada** [comment]
Yes it does.
