### ISSUE TITLE
Gates that call directly the backend

### ISSUE THREAD

**Issue by nquesada** [XanaduAI/strawberryfields#240]
The gates `Xgate`, `Zgate` and `Fourier` do not call the displacement gate and the rotation gate; instead they go directly to the backend. Ideally they should be replaced by `Dgate`s and `Rgate`s with the appropriate parameters.

By not calling the backend directly but instead being replaced by the "canonical" gates with the special values a number of circuit checks can be simplified when calling `Xgate`, `Zgate` and `Fourier`

**Comment by josh146** [comment]
Thanks @nquesada for picking this up. This is a small fix that would lead to big improvements. By treating these gates as decompositions, we have more flexibility within circuit compilation.
