### ISSUE TITLE
Fock-basis backends: State preparations produce density matrices even when it's not necessary

### ISSUE THREAD

**Issue by smite** [XanaduAI/strawberryfields#26]
Preparing a pure state in a subsystem should not convert the entire state representation into a density matrix unless it is necessary. If the reduced state of the rest of the system is pure at the time of the preparation, the entire state remains pure.

Possibly related to #20 

#### Issue description

* *Expected behavior:* State representation remains a ket vector after Fock(1) is executed

* *Actual behavior:* State representation changes into a density matrix

 Also applies to other preparations.

#### Minimal example

    import strawberryfields as sf
    from strawberryfields.ops import *
        
    if __name__ == '__main__':
        backend = 'fock'
        eng, q = sf.Engine(2)
        st = eng.run(backend, cutoff_dim=5)
        print(st)
        with eng:
            Fock(1) | 0
        st = eng.run(backend, cutoff_dim=5)
        print(st)

**Comment by co9olguy** [comment]
We are aware of this and plan to implement it in a future release. While it seems like a simple issue, it requires some caution with the implementation since we will have to track whether the mode(s) where the state is prepared are potentially entangled with other modes.
