### ISSUE TITLE
Orbit cardinality for large number of modes

### ISSUE THREAD

**Issue by hay-k** [XanaduAI/strawberryfields#284]
-------------------------------------------------------------------------------------------------------------

#### Issue description

The function `sf.apps.similarity.orbit_cardinality` does not work, when the second argument (i.e. 'modes') is larger than 170. The issue happens because of the function `scipy.special.factorial`, which, in the way it is used, calculates factorials only up to (including) 170.

Example:
```
>>> import strawberryfields as sf
>>> sf.apps.similarity.orbit_cardinality([2, 1], 171)
```

* *Expected behavior:* Output `29070`

* *Actual behavior:* 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hayk/projects/venv/lib/python3.6/site-packages/strawberryfields/apps/similarity.py", line 278, in orbit_cardinality
    return int(factorial(modes) / np.prod(factorial(counts)))
OverflowError: cannot convert float infinity to integer
```

#### Additional information

The reason behind the issue is, that the function `scipy.special.factorial` with default second argument (i.e. `exact=False`), calculates the factorials in float variables. The factorials of numbers larger than 170 do not fit into a float, hence the function returns `inf`. On the other hand, python can handle large integers, so if we force the factorial funcion to use integers like this
```
return int(factorial(modes, exact=True) / np.prod(factorial(counts, exact=True)))
```
then the issue goes away. Here is the description of the argument 'exact', from scipy documentation: 

> exact: bool, optional
> If True, calculate the answer exactly using long integer arithmetic. If False, result is approximated in floating point rapidly using the gamma function. Default is False.

**Comment by trbromley** [comment]
Thanks @hay-k for the detailed report and the suggested fix. We'll work on this!
