### ISSUE TITLE
Add properties to program that return True/False for when feed-forward or post-selection is used.

### ISSUE THREAD

**Issue by thisac** [XanaduAI/strawberryfields#302]
At the moment there is no _nice_ way of checking whether a circuit has feed-forwarding or post-selection. Currently, it can be done by e.g. (the try-except is needed since not only measurement circuit operations have the select property):

```python
for c in program.circuit:
    try:
        if c.op.select:
            print("post-selection is used")
    except AttributeError:
        pass

    if c.op.measurement_deps:
        print("feed-forwarding is used")
```

It would be much nicer, and less overhead, to have properties in `Program` that return True/False for when feed-forwarding and/or post-selection is used, instead of having to check each operation in the circuit each time you want to run it.

```python
if program.post_selection:
    print("post-selection is used")

if program.feed_forward:
    print("feed-forwarding is used")
```

**Comment by felipeoyarce** [comment]
Hey @thisac, I'm going to tackle this issue :smile:

**Comment by co9olguy** [comment]
Awesome @felipeoyarce! Feel free to open a PR and ask any questions you may have for the team about the implementation.

**Comment by felipeoyarce** [comment]
> Awesome @felipeoyarce! Feel free to open a PR and ask any questions you may have for the team about the implementation.

Thanks @co9olguy! I made the PR but I'm having some issues with the covcode report (is failing in the GitHub Actions).
