### ISSUE TITLE
Numba 0.48 requirement

### ISSUE THREAD

**Issue by antalszava** [XanaduAI/strawberryfields#304]
#### Issue description

The `numba` package has been introduced into SF, however, no version is pinned in `requirements.txt`.

* *Expected behavior:* (What you expect to happen)
Can import Strawberry Fields well.

* *Actual behavior:* (What actually happens)
An error is raised related to `numba`.

* *Reproduces how often:* (What percentage of the time does it reproduce?)
Each time SF is being used.

* *System information:* (post the output of `import stawberryfields as sf; sf.about()`)
    * Python 3.7
    * StrawberryFields==0.13.0.dev0 (latest master)
    * numba==0.43.1

#### Source code and tracebacks
```
ImportError while loading conftest '/xanadu/strawberryfields/tests/conftest.py'.
tests/conftest.py:21: in <module>
    import strawberryfields as sf
strawberryfields/__init__.py:26: in <module>
    from .engine import Engine, LocalEngine, StarshipEngine
strawberryfields/engine.py:26: in <module>
    from .backends import load_backend
strawberryfields/backends/__init__.py:82: in <module>
    from .fockbackend import FockBackend
strawberryfields/backends/fockbackend/__init__.py:16: in <module>
    from .backend import FockBackend
strawberryfields/backends/fockbackend/backend.py:24: in <module>
    from .circuit import Circuit
strawberryfields/backends/fockbackend/circuit.py:27: in <module>
    from numba.typed import List
E   ImportError: cannot import name 'List' from 'numba.typed' (/anaconda3/lib/python3.7/site-packages/numba/typed/__init__.py)
```

If `numba` is not installed, then a simple `numba` import error is emitted.

**Comment by josh146** [comment]
Since `numba` is a hard requirement of SF, we should also add it to `setup.py` (no version pinning needed here for now)

**Comment by antalszava** [comment]
Closing this as https://github.com/XanaduAI/strawberryfields/pull/305 got merged.
