### ISSUE TITLE
Issue with Wigner function on MacOs Safari

### ISSUE THREAD

**Issue by OneDonMateo** [XanaduAI/strawberryfields#308]
Hi!

I cannot see my result when library was changed:

"WebGL is not supported by your browser - visit https://get.webgl.org for more info"

On this page WebGL is fully supported, and works fine

Should I back to chrome?

Thanks!

<img width="611" alt="image" src="https://user-images.githubusercontent.com/18557105/75609383-54df2e80-5b08-11ea-85a0-06da50d0df4f.png">

**Comment by josh146** [comment]
Hi @OneDonMateo, thanks for the bug report! Can I ask you what changed that caused you to see this message --- does it still work fine in Chrome?

**Comment by OneDonMateo** [comment]
Same issue there.
Maybe it's related to my old saved structures (old diagrams). I can create new and let you know...

**Comment by co9olguy** [comment]
Just speculating @josh146 but maybe an update to plotly caused this issue?

**Comment by josh146** [comment]
Can confirm this occurs for me on both Chrome and Firefox. As there have been no updates on our end, I'm guessing you're right --- a plot.ly update is causing the issue.

**Comment by josh146** [comment]
This is now fixed thanks to @antalszava!
