### ISSUE TITLE
Will you have examples w.r.t. deep or machine learning with strawberry fields?  Thanks!

### ISSUE THREAD

**Issue by shyamalschandra** [XanaduAI/strawberryfields#33]
Will you have examples w.r.t. deep or machine learning with strawberry fields?  Thanks!

**Comment by co9olguy** [comment]
Hi there, thanks for your interest in Strawberry Fields. 
There are several ML examples already available in both this repository and its sister repos. 

For example:
https://strawberryfields.readthedocs.io/en/latest/tutorials/tutorial_machine_learning.html
https://qmlt.readthedocs.io/en/latest/tutorials/numerical.html
https://qmlt.readthedocs.io/en/latest/tutorials/tensorflow.html
https://github.com/XanaduAI/quantum-learning

We also have several research papers for some of these topics, which are freely available:
https://arxiv.org/abs/1806.06871
https://arxiv.org/abs/1807.10781

We will also be releasing another repo with more example ML code sometime relatively soon. Stay tuned!
