### ISSUE TITLE
Typos in quantum teleportation tutorial code

### ISSUE THREAD

**Issue by mariaschuld** [XanaduAI/strawberryfields#332]
#### Issue description

Teleportation tutorial code is not executable due to 2 typos:

1. Wrong use of dictionary [EDIT: this seems to be fixed already in the latest master]:

``result = eng.run(prog, run_options={shots=1, modes=None}, compile_options={})``

2. Variable ``results`` not declared (should be ``result``):

``results.samples``

The inconsistent use of ``results`` instead of  ``result`` is also in the text here:

![Screenshot from 2020-03-24 08-50-16](https://user-images.githubusercontent.com/23052011/77396522-946a0500-6dac-11ea-8244-587405a324d9.png)

**Comment by josh146** [comment]
This appears to have been fixed in #337
