### ISSUE TITLE
`run()` has inconsistent signatures for the local and remote engines

### ISSUE THREAD

**Issue by josh146** [XanaduAI/strawberryfields#335]
While working on #334, I noticed that the `LocalEngine` and `RemoteEngine` have inconsistent signatures. In particular:

* `LocalEngine.run()`:

  ```python3
  run(self, program, *, args=None, compile_options=None, run_options=None):
  ```

* `RemoteEngine.run()`:

  ```python3
  run(self, program: Program, shots: Optional[int] = None):
  ```

This leads to the odd case where running a program for 50 shots looks like
```python
eng.run(prog, run_options={"shots": 50})
```
on the local engine (here, `run_options` passes *runtime specific* options directly to the backend `Operation.apply()` methods), but looks like
```python
eng.run(prog, shots=50)
```
on the remote engine.

**Comment by antalszava** [comment]
#327 might be relevant as a whole and had a review comment there which might also be connected
