### ISSUE TITLE
suspected typo in docs

### ISSUE THREAD

**Issue by tymomboe** [XanaduAI/strawberryfields#338]
## Issue description

Description of the issue - running
>>> sf.cli.ping()
gives an error.
(this is taken directly from the SF docs page on 
Suspected "cli" is a typo.  

Found here: https://strawberryfields.readthedocs.io/en/latest/introduction/photonic_hardware.html

**Comment by antalszava** [comment]
Thanks so much for this @tymomboe! Created a PR that should resolve this.

**Comment by josh146** [comment]
Fixed by #340
