### ISSUE TITLE
Blackbird Program Compliation Bug

### ISSUE THREAD

**Issue by heltluke** [XanaduAI/strawberryfields#368]
#### Issue description

* *Expected behavior:* (What you expect to happen)

If I attempt to compile a program, specifying only a portion of a the modes on an X8 chip, for anything other than an identity operation (for I understand SF will fill in unspecified modes with an identity operation) I expect a `CircuitError`.

* *Actual behavior:* (What actually happens)

The program
```
MZgate(0, 0) | (q[0], q[1])
MZgate(0, 0) | (q[1], q[2])
MZgate(0, 0) | (q[0], q[1])
MZgate(0, 0) | (q[0], q[1])
MZgate(0, 0) | (q[1], q[2])
MZgate(0, 0) | (q[0], q[1])
MeasureFock | (q[0], q[1], q[2], q[3], q[4], q[5], q[6], q[7])
```
compiles as
```
S2gate(0, 0) | (q[0], q[4])
S2gate(0, 0) | (q[3], q[7])
S2gate(0, 0) | (q[2], q[6])
S2gate(0, 0) | (q[1], q[5])
MZgate(3.142, 0) | (q[0], q[1])
MZgate(3.142, 0) | (q[2], q[3])
MZgate(3.142, 3.142) | (q[1], q[2])
MZgate(3.142, 3.142) | (q[0], q[1])
MZgate(3.142, 0) | (q[2], q[3])
MZgate(3.142, 3.142) | (q[1], q[2])
Rgate(3.142) | (q[0])
Rgate(0) | (q[1])
Rgate(0) | (q[2])
Rgate(0) | (q[3])
MZgate(3.142, 0) | (q[4], q[5])
MZgate(3.142, 0) | (q[6], q[7])
MZgate(3.142, 3.142) | (q[5], q[6])
MZgate(3.142, 3.142) | (q[4], q[5])
MZgate(3.142, 0) | (q[6], q[7])
MZgate(3.142, 3.142) | (q[5], q[6])
Rgate(3.142) | (q[4])
Rgate(0) | (q[5])
Rgate(0) | (q[6])
Rgate(0) | (q[7])
MeasureFock | (q[0], q[1], q[2], q[3], q[4], q[5], q[6], q[7])
```
without raising an error.

* *Reproduces how often:* (What percentage of the time does it reproduce?)

100% of the time

* *System information:* (post the output of `import strawberryfields as sf; sf.about()`)

Strawberry Fields: a Python library for continuous-variable quantum circuits.
Copyright 2018-2020 Xanadu Quantum Technologies Inc.

Python version:            3.7.6
Platform info:             Linux-5.3.0-46-generic-x86_64-with-debian-buster-sid
Installation path:         /home/heltluke/anaconda3/envs/sf_latest/lib/python3.7/site-packages/strawberryfields
Strawberry Fields version: 0.13.0.rc0
Numpy version:             1.18.1
Scipy version:             1.4.1
SymPy version:             1.5.1
NetworkX version:          2.4
The Walrus version:        0.12.0
Blackbird version:         0.2.3
TensorFlow version:        None

#### Source code and tracebacks

This happened due to a bug in a script I wanted to use to generate a program using MZI gates from an array of phases. I thought I was creating an "anti-identity" operation on modes 0-4, instead I created the program above
```
phases = np.zeros(12)

prog = sf.Program(8)
with prog.context as q:
    for mzi_index in range(6):
        in_block_index = mzi_index % (4 - 1)
        upper_mode = in_block_index % 2
        sf.ops.MZgate(
            phases[mzi_index * 2], phases[mzi_index * 2 + 1]
        ) | (q[upper_mode], q[upper_mode + 1])
    sf.ops.MeasureFock() | q

prog.compile("X8").print()
```

**Comment by heltluke** [comment]
I note that even the compiled version of 
```
prog = sf.Program(8)
with prog.context as q:
    sf.ops.Interferometer(np.identity(4)) | (q[0], q[1], q[2], q[3])
    sf.ops.MeasureFock() | q
```
is not the same as the compiled version of
```
prog = sf.Program(8)
with prog.context as q:
    sf.ops.Interferometer(np.identity(4)) | (q[0], q[1], q[2], q[3])
    sf.ops.Interferometer(np.identity(4)) | (q[4], q[5], q[6], q[7])
    sf.ops.MeasureFock() | q
```

**Comment by nquesada** [comment]
@heltluke : I am not sure if I follow why is this a bug. All the programs you wrote are instructions for preparing vacuum in all the modes.

**Comment by heltluke** [comment]
>All the programs you wrote are instructions for preparing vacuum in all the modes.

This was just to reduce the number of lines copied and pasted above, as I'm concerned with how `prog.compile("X8")` works in terms of the interferometer phases that are set, and I don't need to specify
```
for i in range(n_modes):
    sf.ops.S2gate(1) | (q[i], q[i + n_modes])
```
for compilation to work.

I guess it's a question of desired vs (my) expected behaviour. What happens is potentially intentional, it's just a surprise to me. I would have expected the default / unspecified / "identity" interferometer to be
```
MZgate(pi, 0) | (q[0], q[1])
MZgate(pi, 0) | (q[2], q[3])
MZgate(pi, 0) | (q[1], q[2])
MZgate(pi, 0) | (q[0], q[1])
MZgate(pi, 0) | (q[2], q[3])
MZgate(pi, 0) | (q[1], q[2])
Rgate(0) | (q[0])
Rgate(0) | (q[1])
Rgate(0) | (q[2])
Rgate(0) | (q[3])
MZgate(pi, 0) | (q[4], q[5])
MZgate(pi, 0) | (q[6], q[7])
MZgate(pi, 0) | (q[5], q[6])
MZgate(pi, 0) | (q[4], q[5])
MZgate(pi, 0) | (q[6], q[7])
MZgate(pi, 0) | (q[5], q[6])
Rgate(0) | (q[4])
Rgate(0) | (q[5])
Rgate(0) | (q[6])
Rgate(0) | (q[7])
```
and see seeing all of the extra factors of pi around is what's surprising to me.

**Comment by nquesada** [comment]
I think the issue with the pis comes from the rectangular symmetric decomposition. Indeed if you
`sf.decompositions.rectangular_symmetric(np.identity(4))`
you get
`
([[0, 1, 3.141592653589793, 0.0, 4], 
  [2, 3, 3.141592653589793, 0.0, 4],
  [1, 2, 3.141592653589793, 3.141592653589793, 4],
  [0, 1, 3.141592653589793, 3.1415926535897936, 4],
  [2, 3, 3.141592653589793, 0.0, 4],
  [1, 2, 3.141592653589793, 3.1415926535897927, 4]],
 array([-1.+5.6655389e-16j,  1.-4.8985872e-16j,  1.-2.4492936e-16j,  1.+0.0000000e+00j]),
 None)
`
which seems to have all the pis that appear in your decompositions. Maybe @ishdhand or @shreyapkumar  can comment?

**Comment by josh146** [comment]
Good catch @nquesada, perhaps this is fixed in #363?

**Comment by heltluke** [comment]
Right, so the default is
```
MZgate(3.142, 0) | (q[0], q[1])
MZgate(3.142, 0) | (q[2], q[3])
MZgate(3.142, 3.142) | (q[1], q[2])
MZgate(3.142, 3.142) | (q[0], q[1])
MZgate(3.142, 0) | (q[2], q[3])
MZgate(3.142, 3.142) | (q[1], q[2])
```
I guess it's simply coincidence that my "swap and swap back" sequence of gates
```
MZgate(0, 0) | (q[0], q[1])
MZgate(0, 0) | (q[1], q[2])
MZgate(0, 0) | (q[0], q[1])
MZgate(0, 0) | (q[0], q[1])
MZgate(0, 0) | (q[1], q[2])
MZgate(0, 0) | (q[0], q[1])
``` 
has the same "external" phases? What about the Rgates?

**Comment by heltluke** [comment]
>perhaps this is fixed in #363

That PR looks awesome!

**Comment by nquesada** [comment]
I am not so sure anymore. What is the unitary decomposition used by the `X8` compiler?

**Comment by shreyapkumar** [comment]
> perhaps this is fixed in #363?
This shouldn't be fixed there. What I wrote should (hopefully) give the same results as `rectangular_symmetric`

**Comment by shreyapkumar** [comment]
Actually, reading @heltluke first post: https://github.com/XanaduAI/strawberryfields/issues/368#issue-600426936 more carefully, this is the behaviour one would expect, no, except for some of the external phases which are pi. The input was a series of swaps which all cancel one another, so the output is just "bars" in all the MZIs.

**Comment by heltluke** [comment]
Yeah, I've come to see that it's "bars"for modes 0, 1, and 2. My concern is about the second arguments of the MZgates and the arguments of the Rgates. If "identity" is
```
MZgate(pi, 0) | (q[0], q[1])
MZgate(pi, 0) | (q[2], q[3])
MZgate(pi, pi) | (q[1], q[2])
MZgate(pi, pi) | (q[0], q[1])
MZgate(pi, 0) | (q[2], q[3])
MZgate(pi, pi) | (q[1], q[2])
Rgate(pi) | (q[0])
Rgate(0) | (q[1])
Rgate(0) | (q[2])
Rgate(0) | (q[3])
```
was it just coincidence that
```
MZgate(0, 0) | (q[0], q[1])
MZgate(0, 0) | (q[1], q[2])
MZgate(0, 0) | (q[0], q[1])
MZgate(0, 0) | (q[0], q[1])
MZgate(0, 0) | (q[1], q[2])
MZgate(0, 0) | (q[0], q[1])
```
comes out the same?

**Comment by shreyapkumar** [comment]
If I understand correctly, all these input MZ gates are first complied by being multiplied together (in this case it would multiply to the identity). Then the decomposition sees no difference between these MZ gates and when you input the identity matrix.

**Comment by heltluke** [comment]
I mean, I guess it does, right? Two rotations of pi on q[0] and q[2] effectively cancel. But the point is that they require different settings on the hardware

**Comment by heltluke** [comment]
Perhaps the clearest way of stating what I expected is that I expected the check of whether the circuit for modes 0-3 matches the circuit for modes 4-7 during compiling on X8 to verify that the circuit for modes 0-3 was "the" identity and not merely "an" identity (and also not for compilation to subsequently alter whatever identity operation I'd set up on modes 0-3).

**Comment by shreyapkumar** [comment]
My understanding is that if you dont have access to the low level interface, SF compiles everything. So a series of "swap and swap back" would first get compiled and become the identity. Then the rectangular decomposition gives identical results for such a series of MZIs and the identity. 

When I tried to fix the identity decomposition, I was only able to fix the internal phases (now hopefully they are all pi), but the external phases are somewhat arbitrary.

**Comment by heltluke** [comment]
Thanks @shreyapkumar. I think it's OK to close this then, as it's more user error than a "bug". If one wants to specify phases, they must specify ALL in a sequence such as
```
MZgate(phi1, phi2) | (q[0], q[1])
MZgate(phi3, phi4) | (q[2], q[3])
MZgate(phi5, phi6) | (q[1], q[2])
MZgate(phi7, phi8) | (q[0], q[1])
MZgate(phi9, phi10) | (q[2], q[3])
MZgate(phi11, phi12) | (q[1], q[2])
Rgate(0) | (q[0])
Rgate(0) | (q[1])
Rgate(0) | (q[2])
Rgate(0) | (q[3])
MZgate(phi1, phi2) | (q[4], q[5])
MZgate(phi3, phi4) | (q[6], q[7])
MZgate(phi5, phi6) | (q[5], q[6])
MZgate(phi7, phi8) | (q[4], q[5])
MZgate(phi9, phi10) | (q[6], q[7])
MZgate(phi11, phi12) | (q[5], q[6])
Rgate(0) | (q[4])
Rgate(0) | (q[5])
Rgate(0) | (q[6])
Rgate(0) | (q[7])
```
