### ISSUE TITLE
Gaussian Boson Sampling preset parameters error

### ISSUE THREAD

**Issue by Luca-Ca** [XanaduAI/strawberryfields#369]
In the GBS preset on Strawberry Fields Interactive the first beam-splitter has a factor 2*pi error in the parameters. 

I am pretty sure it's the case by comparing to the circuit in ("https://strawberryfields.readthedocs.io/en/stable/tutorials/tutorial_boson_sampling.html#boson-tutorial") and because I ran simulations to calculate the marginal probabilities outputs and they agree with the Interactive results when I either multiply by 2*pi the parameters in the python tutorial or divide by 2*pi the parameters in the preset.

![GBS2](https://user-images.githubusercontent.com/63753893/79392322-848cad80-7f73-11ea-847b-fad0d5e88811.png)

![GBS1](https://user-images.githubusercontent.com/63753893/79392203-4d1e0100-7f73-11ea-8f7d-3f107135a6c8.png)

**Comment by antalszava** [comment]
Hi @Luca-Ca, thanks so much for letting us know about this! :blush: We'll look into it and let you know about further details.

**Comment by antalszava** [comment]
Hi @Luca-Ca, thank you again for pointing this out! :blush:

We have updated the Boson sampling preset algorithm where the issue occurred (one thing to note is that this is different from the Gaussian Boson sampling preset algorithm).

Now, this circuit should match the one found in the tutorial.
