### ISSUE TITLE
Tensorflow-gpu 1.6 yields an obscure bug

### ISSUE THREAD

**Issue by ziofil** [XanaduAI/strawberryfields#39]
#### Issue description
Utilizing `tensorflow-gpu` v1.6 with `strawberryfields-gpu` sometimes results in unnormalised states.
The hardware is an Nvidia V100, but I've also reproduced it on an Nvidia K80.

#### System information
* **Operating system:**
ubuntu 16.04

* **Strawberry Fields version:**
v0.9

* **Python version:**
3.6.8

* **NumPy, SciPy, and Tensorflow versions:**
numpy 1.15.1, scipy 1.1.0, tensor flow-gpu 1.6.0 and CUDA 9

* **Installation method:**
pip

#### Source code and tracebacks
I can reproduce it, but the code is fairly long, definitely not a 'snippet'

#### Additional information
I have tested 19 versions and builds of tensorflow. The bug appears on 1.6, 1.7 and 1.10, but I'll ignore 1.7 and 1.10 because in any case they're not supported by strawberryfields.

**Comment by co9olguy** [comment]
Thanks for the bug report @ziofil!
I'm hoping having it here might make it easier for us to track down the source of the bug.

**Comment by josh146** [comment]
Since we no longer support TF v1.6 with release 0.11, marking this as closed.
