### ISSUE TITLE
 ValueError: 'thewalrus/libwalrus.pyx' doesn't match any files. how to solve this for installation?

### ISSUE THREAD

**Issue by sassan72** [XanaduAI/strawberryfields#408]
#### Before posting an issue

Search existing GitHub issues to make sure the issue does not already exist:
https://github.com/xanaduai/strawberryfields/issues

If posting a Strawberry Fields issue, delete everything above the dashed line, and fill
in the template.

If making a feature request, delete the following template and describe, in detail,
the feature and why it is needed.

For general technical details. check out our documentation:
https://strawberryfields.readthedocs.io

-------------------------------------------------------------------------------------------------------------

#### Issue description

Description of the issue - include code snippets and screenshots here
if relevant. You may use the following template below

* *Expected behavior:* (What you expect to happen)

* *Actual behavior:* (What actually happens)

* *Reproduces how often:* (What percentage of the time does it reproduce?)

* *System information:* (post the output of `import strawberryfields as sf; sf.about()`)

#### Source code and tracebacks

Please include any additional code snippets and error tracebacks related
to the issue here.

#### Additional information

Any additional information, configuration or data that might be necessary
to reproduce the issue.

**Comment by josh146** [comment]
Hi @sassan72! Can I ask for some additional information in diagnosing this issue. In particular,

* What operating system are you using?

* What version of Python are you using? This can be checked by running `python --version` in the terminal.

Thanks!

**Comment by sassan72** [comment]
python 3.7, Mac OS Sierra.

**Comment by josh146** [comment]
Hmm, that should be a supported version of Python 🤔 

Are your using the built-in Python that ships with MacOS, or are you using Anaconda?

**Comment by sassan72** [comment]
actually, I installed python with pip install python. i have also Anaconda. do you think the problem is related to my Python library.

**Comment by josh146** [comment]
Potentially, could you try installing it using Anaconda?

**Comment by sassan72** [comment]
Thanks Josh for helping. you mean by conda install

**Comment by antalszava** [comment]
Hi @sassan72!

One way you could have Python be installed with Anaconda is to [create a new environment with Anaconda](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-python.html#installing-a-different-version-of-python).

For example, you could create a new Anaconda environment the following way:
`conda create --name py36 python=3.6`

After that, you could activate this environment on macOS by:
`source activate py36`

At this step, you will have an environment that has a few basic packages installed. You could then use `pip` to install TheWalrus.

Let us know how this goes!

**Comment by antalszava** [comment]
Hi @sassan72, any updates here?

**Comment by sassan72** [comment]
I could install it. thanks.
