### ISSUE TITLE
Bug in the Quantum State Learning notebook

### ISSUE THREAD

**Issue by artix41** [XanaduAI/strawberryfields#45]
#### Issue description

When trying to run [this gallery notebook](https://github.com/XanaduAI/strawberryfields/blob/master/doc/gallery/state_learner/StateLearning.ipynb), at first execution of the line:
```python
_, cost_val, fid_val, ket_val = session.run([min_cost, cost, fidelity, ket])
```
the kernel dies with the error:
```bash
F ./tensorflow/core/kernels/transpose_functor.h:169] Check failed: in.dims() >= 2 (1 vs. 2)
```

#### System information

* **Operating system:**
 
Ubuntu Linux 16.04

* **Anaconda environment**
  
```bash
python=3.6.5=1
numpy=1.14.3=py36h28100ab_2
pip=9.0.3=py36_0
StrawberryFields==0.9.0
tensorboard==1.6.0
tensorflow==1.6.0
```

**Comment by josh146** [comment]
Thanks @artix41. We've had this reported through other channels the last week or so, and it looks like a bug in TensorFlow v1.6; specifically, this bug is related to taking the `tf.conj()` function. While we're still tracking it down, a solution is to temporarily downgrade to TensorFlow v1.3

**Comment by artix41** [comment]
Ok, thanks for you quick reply, I will use TF 1.3 in the meantime.
