### ISSUE TITLE
The link to `contribution guidelines` is incorrect in CHALLENGES.md

### ISSUE THREAD

**Issue by rochisha0** [XanaduAI/strawberryfields#453]
#### Issue description

Description of the issue - include code snippets and screenshots here
if relevant. You may use the following template below

* *Expected behavior:* (What you expect to happen)
Link to https://github.com/XanaduAI/strawberryfields/blob/master/.github/CONTRIBUTING.md

* *Actual behavior:* (What actually happens)
Page not found

**Comment by josh146** [comment]
Thanks @rochisha0 for catching this! This has been fixed in #454

**Comment by rochisha0** [comment]
Ok. I was interested in creating PR but nevermind!

**Comment by josh146** [comment]
Sorry @rochisha0! Feel free to open PRs directly as soon as you see something like that that needs to be corrected 🙂
