### ISSUE TITLE
Inconsistency in tensorflow version requirements in /doc

### ISSUE THREAD

**Issue by ilan-tz** [XanaduAI/strawberryfields#465]
development/development_guide.rst lists tensorflow 1.3 as the requirement, whereas introduction/circuits.rst lists tensorflow 2.0. The former should be changed to 2.0

**Comment by mariaschuld** [comment]
Hey @ilan-tz! Good catch, you are right: the development guide is outdated. Would you mind making a pull request fixing this bug?

**Comment by co9olguy** [comment]
Closed by #468
