### ISSUE TITLE
Bug with tensorflow backend

### ISSUE THREAD

**Issue by ccortes888** [XanaduAI/strawberryfields#485]
-------------------------------------------------------------------------------------------------------------

#### Issue description

Bug occurs with tensorflow backend. It arises in the following program:

```
import strawberryfields as sf
from strawberryfields.ops import *
import numpy as np

prog = sf.Program(2)
eng  = sf.Engine("tf", backend_options={"cutoff_dim": 50})
with prog.context as q:
    Sgate(0.8)         | q[0]
    Sgate(0.8)         | q[1]
    BSgate(0.5,0.5)  | (q[0], q[1])
    BSgate(0.5,0.5)  | (q[0], q[1])
state    = eng.run(prog).state
N0,N0var = state.mean_photon(0)
N1,N1var = state.mean_photon(1)
print(N0)
print(N1)
print('analytical:',np.sinh(0.8)**2)
```

* *Expected behavior:* (What you expect to happen)

The output from N0 and N1 should be equal to sinh(0.8)**2.

* *Actual behavior:* (What actually happens)

Output gives a numeric value of 0.8611656. 

* *Reproduces how often:* (What percentage of the time does it reproduce?)

Depends on the cutoff_dim. Below 47, it seems to give an approximately correct result. Above 47, the result deviates from expected answer. The result becomes worse for larger cutoff dimensions. Note also that the "Fock" backend gives the correct result even for large cutoff dimensions. This seems to be an issue with the tensorflow backend. 

* *System information:* (post the output of `import strawberryfields as sf; sf.about()`)
```
Strawberry Fields: a Python library for continuous-variable quantum circuits.
Copyright 2018-2020 Xanadu Quantum Technologies Inc.
Python version:            3.7.9
Platform info:             Darwin-17.7.0-x86_64-i386-64bit
Strawberry Fields version: 0.15.1
Numpy version:             1.19.2
Scipy version:             1.5.2
SymPy version:             1.6.2
NetworkX version:          2.5
The Walrus version:        0.13.0
Blackbird version:         0.2.4
TensorFlow version:        2.4.0-dev20201019
```

**Comment by nquesada** [comment]
Thanks for the report @ccortes888 . A possible explanation is that the `float32` type being used by `tf` is not enough to give a numerically correct calculation.

**Comment by ccortes888** [comment]
Thanks @nquesada. Would it be possible to change type to float64?

**Comment by nquesada** [comment]
Hey. You could change this line https://github.com/XanaduAI/strawberryfields/blob/9800240e014d9b2844444cf92fd1b17b581dfa06/strawberryfields/backends/tfbackend/ops.py#L67

I tested it and you do get the correct result.

**Comment by ccortes888** [comment]
Just tested it. Works for me too. Thanks Nicolas!

**Comment by co9olguy** [comment]
@nquesada @josh146 Should we consider making this a user-adjustable setting, e.g., when instantiating the engine?

**Comment by nquesada** [comment]
It does sound like a useful addition.

**Comment by josh146** [comment]
Agree

**Comment by co9olguy** [comment]
Done.
@ccortes888 if you might like to contribute to the library, this would be a relatively straightforward feature to add :smiley:
