### ISSUE TITLE
PyTorch backend

### ISSUE THREAD

**Issue by sonamghosh** [XanaduAI/strawberryfields#49]
Given the amount of work in ML community of academia being implemented on PyTorch, can Strawberry Fields interface with any sort of project that's using PyTorch instead of using the existing Tensorflow backend in SF? 
(Disclaimer: Accidentally put this issue in the wrong repo before this, however,  I closed it afterwards so all good now) .

**Comment by josh146** [comment]
Hi @sonamghosh. The main reason there is currently no PyTorch backend in Strawberry Fields is that PyTorch (unlike TensorFlow) has no support for complex numbers and complex-valued functions. Some useful links regarding this issue include:

* The main GitHub issue in which complex number support is discussed: https://github.com/pytorch/pytorch/issues/755

* Work in progress complex-valued tensor support for PyTorch: https://github.com/Roger-luo/pytorch-complex

* Another repository working on unofficial complex tensor support in PyTorch: https://github.com/williamFalcon/pytorch-complex-tensor

This is something we would love to add if and when PyTorch supports complex maths!

**Comment by josh146** [comment]
Note that our quantum machine learning library, https://github.com/XanaduAI/pennylane, supports both TensorFlow _and_ PyTorch.

PennyLane is designed for hybrid quantum-classical computation, with the quantum backpropagation calculated via querying quantum hardware devices directly, and the classical portion of the backpropagation using a ML backend such as TF/PyTorch.
