### ISSUE TITLE
TensorFlow 2.0 support?

### ISSUE THREAD

**Issue by josh146** [XanaduAI/strawberryfields#50]
TensorFlow 2.0 is expected to be released this year. The changes expected include:

* Semantic versioning (so should be much easier to maintain against)

* An eager-first interface. Eager execution mode will be moved out of `tf.contrib` and will become the default way of working with TensorFlow.

* A focus on keras as the high-level API, as opposed to the Estimator class.

For more details, see
* https://medium.com/tensorflow/test-drive-tensorflow-2-0-alpha-b6dd1e522b01?linkId=64437259
* https://medium.com/tensorflow/whats-coming-in-tensorflow-2-0-d3663832e9b8
* https://medium.com/tensorflow/standardizing-on-keras-guidance-on-high-level-apis-in-tensorflow-2-0-bad2b04c819a
* https://www.tensorflow.org/alpha

Rather than focus on updating the existing TensorFlow backend to support 1.7+, I suggest a focus on implementing a TF2 compatible backend. This could be a fork of the existing TF backend, and marking the existing TF backend as 'legacy'.

**Comment by co9olguy** [comment]
This is a significant change; enough so that we would need to think on whether we want to support TF2.0+, or keep the existing TF backend (with v1+ graph-based approach)

**Comment by josh146** [comment]
This is a good point; I'm in favor of completely deprecating/dropping the existing TF backend for a TF2.0 compatible one.

In terms of research reproducibility, and existing research repositories, it should be matter of explicitly stating 'this research code requires you `pip install strawberryfields==0.9 tensorflow==1.3`, and does not work with later versions of SF or TF'
