### ISSUE TITLE
Broken link for "Request access" button

### ISSUE THREAD

**Issue by lneuhaus** [XanaduAI/strawberryfields#525]
Description of the issue - include code snippets and screenshots here
if relevant. You may use the following template below

* *Expected behavior:* (What you expect to happen)

Link "request access" on https://strawberryfields.ai/ and in the documentation should work.

* *Actual behavior:* (What actually happens)

The link is broken.

* *Reproduces how often:* (What percentage of the time does it reproduce?)

Every time.

* *System information:* (post the output of `import strawberryfields as sf; sf.about()`)

Not relevant.

#### Additional information

The broken link points to https://xanadu.ai/request-access, while the correct address seems to be https://xanadu.ai/access

**Comment by mariaschuld** [comment]
This seems to be fixed now. Thanks for reporting @lneuhaus.
