### ISSUE TITLE
Missing negative sign in docs for sf.ops.S2gate

### ISSUE THREAD

**Issue by akirakyle** [XanaduAI/strawberryfields#550]
On line [1887 of ops.py](https://github.com/XanaduAI/strawberryfields/blob/50ae64ad94e78ca02ea0b081148178551bff554b/strawberryfields/ops.py#L1887) a minus sign is missing in the RHS expression. It should be `e^{i\phi} a_1^\dagger a_2^\dagger - e^{-i\phi} a_1 a_2`.

**Comment by nquesada** [comment]
Thanks for spotting this typo @akirakyle ! It is no addressed in [#551].
