### ISSUE TITLE
update the PR template

### ISSUE THREAD

**Issue by jakeffbulmer** [XanaduAI/strawberryfields#585]
In the PR template, it says: "Ensure that code is properly formatted, by running make format or black -l 100 strawberryfields. You will need to have the Black code format installed: pip install black."

If you run this, it will change ~80 files, mostly in doc and tests, which would crowd any of the intentional changes of the PR, and maybe cause unwanted changes in these files. Perhaps it could say:

"Ensure that code is properly formatted, by running ``black -l 100 <filename>`` on any relevant files. You will need to have the Black code format installed: ``pip install black``. Please do not run on test files."

**Comment by josh146** [comment]
Thanks @jakeffbulmer! Ah, I see the issue now: we wrote `black -l 100 strawberryfields` assuming you are already in the main repo (so at the same level as the `setup.py`) and are instead blacking the _interior_ `strawberryfields` folder.

Regarding the test: we actually should black the tests :) However, probably best to do this in a separate PR!
