### ISSUE TITLE
Gaussian Compilers Primitive and Decomposition definitions need to be fixed

### ISSUE THREAD

**Issue by federico0112** [XanaduAI/strawberryfields#593]
#### Issue description

Gaussian compilers currently define measurement operations as primitives, which should not be the case. Furthermore, Gaussian state decompositions are defined in the Gaussian compilers decomposition, which is not ideal.

**Comment by nquesada** [comment]
It seemed like good idea to make explicit that a compiler only operates on operation and not measurements and preparations, but this is too overzealous. For the moment we will allow compiler to still have these operations.
