### ISSUE TITLE
Remove the ability to set some hyperparameters in the test suite

### ISSUE THREAD

**Issue by josh146** [XanaduAI/strawberryfields#60]
At the moment, the test suite currently accepts Fock basis cutoff dimension as a test hyperparameter. However, I've noticed that this is something very rarely used, and every single test in the test suite is written to pass with a cutoff dimension of 6 (the current default).

I suggest we remove this as a test parameter/fixture, and simply use 6 as the global default, while allowing tests to override this default if needed. This is better for three reasons:

* It removes any confusion from a user passing a specific cutoff parameter to the test suite, and not realising that some tests override this

* it is better practice to write tests for a particular fixed cutoff value

* It is near impossible to write tests that will pass for any cutoff value. Tests which we know work could fail simply by passing `--cutoff=5` rather than the default of 6, which is poor UX for a user.

**Comment by co9olguy** [comment]
> every single test in the test suite is written to pass with a cutoff dimension of 6 (the current default)

Except for the ones that don't :smiley_cat:

**Comment by co9olguy** [comment]
Anyway, I think this is a good change, will make things much more clear, and is pretty easy to do (just remove the user's ability to change this)

**Comment by thisac** [comment]
Closing obsolete issue. Fixed when porting test suite to pytest in v0.10.0.
