### ISSUE TITLE
Bosonic backend in documentation

### ISSUE THREAD

**Issue by nquesada** [XanaduAI/strawberryfields#609]
It would be nice to update this figure:

![image](https://user-images.githubusercontent.com/991946/126009809-4d55f755-71de-494c-9242-958372038356.png)

from https://strawberryfields.readthedocs.io/en/stable/code/sf.html

to reflect the fact that there is a new `bosonic` backend in the library.

**Comment by sduquemesa** [comment]
@nquesada, updating it to this figure:

![sfcomponents](https://user-images.githubusercontent.com/675763/134428699-0cbffcdf-d391-49d3-8cf2-fdaa0902f731.png)
