### ISSUE TITLE
Why add batch on last dimension?

### ISSUE THREAD

**Issue by ziofil** [XanaduAI/strawberryfields#75]
It may not matter in the end, but shouldn't [these lines](https://github.com/XanaduAI/strawberryfields/blob/80191c7a0d6b3430ba31228e0e53ffb5c496dfab/strawberryfields/backends/tfbackend/ops.py#L292) be 

```python
t = tf.expand_dims(t, 0)
r = tf.expand_dims(r, 0)
```

to match what is done in the other ops?

**Comment by co9olguy** [comment]
Thanks @ziofil! 
I don't expect it to make any functional difference, but it is clearer this way when people are reading code.
Fixed in latest master
