### ISSUE TITLE
Migrate to number version of einsum

### ISSUE THREAD

**Issue by ziofil** [XanaduAI/strawberryfields#76]
I've been reading the code lately, and I've noticed that you make heavy use of einsum with the string notation, e.g.
```python
einsum('ij,jk->ik', A, B)
```
Einsum supports also numerical specs instead of letters (same example as above):
```python
einsum(A, [0,1], B, [1,2], [0,2])
```
Given that you need a lot of index gymnastic, I think it could be beneficial to change the standard and adopt the numerical version of the indices. I used it in my contribution and it allowed my code to be quite compact (I don't even want to think what it would have been like to do the same with letters!)

This could also allow you to be more consistent in the code across the various ops (at the moment it seems that each op was coded by a different person 😅).

**Comment by ziofil** [comment]
Darn it, I just remembered that only the bumpy version of einsum supports it...

**Comment by co9olguy** [comment]
Thanks anyway for the suggestion @ziofil!
