### ISSUE TITLE
Details about the configuration options

### ISSUE THREAD

**Issue by co9olguy** [XanaduAI/strawberryfields#98]
Details about the configuration options --- I left this blank as this is still a WIP, and best filled in by @zzzeid as part of #93

_Originally posted by @josh146 in https://github.com/XanaduAI/strawberryfields/pull/94_

Relevant details for SF config file should be entered as part of #93

**Comment by co9olguy** [comment]
@josh146 I'd like to include configuration into latest release, since it is already merged and the only piece missing is some extra documentation. 

What do you suggest regarding the current todo in configuration options? Can we just omit that section from docstring for now?

Or is this something that can be safely moved into a holding area and not released officially until the next release?

**Comment by josh146** [comment]
> What do you suggest regarding the current todo in configuration options? Can we just omit that section from docstring for now?

Until the API client is included, no configuration options are currently available to be set/described in the configuration module. So if we do include it, we would just omit that section from the docstring.

> Or is this something that can be safely moved into a holding area and not included officially until the next release?

May as well keep it in the release if it's easier - it doesn't affect any other part of the codebase.

**Comment by co9olguy** [comment]
Since the configuration module exists, but doesn't yet do anything, it makes more sense to move it to an unofficial part of the codebase, and wait until next release before officially incorporating it. I will do that now

**Comment by josh146** [comment]
Closed via #110
